sonar.projectKey=crud-clientes-devops
sonar.projectName=CRUD Clientes DevOps
sonar.projectVersion=2.0.0

sonar.sources=backend/src,frontend
sonar.tests=backend/tests,frontend/tests

sonar.python.version=3.13
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
**/__pycache__/**,\
**/*.pyc,\
frontend/node_modules/**,\
frontend/coverage/**,\
frontend/tests/**

sonar.test.inclusions=\
backend/tests/**/*.py,\
frontend/tests/**/*.js

sonar.sourceEncoding=UTF-8